spring:
  datasource:
    url: jdbc:mariadb://localhost:33360/petBrunch
    username: petBrunch
    password: petBrunch
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000

  h2:
    console.enabled: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace